services:
  e2echatapp:
    image: e2echatapp
    build:
      context: E2E-Backend
      dockerfile: E2E-Backend/E2EChatApp/Dockerfile
    ports:
      - 5000:80

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: E2EDatabase
    ports:
      - 5432:5432
    volumes:
      - ./seeds:/docker-entrypoint-initdb.d
