// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace E2EChatAppSpecFlow.Features.Services
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FriendServiceFeature : object, Xunit.IClassFixture<FriendServiceFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Friendship.feature"
#line hidden
        
        public FriendServiceFeature(FriendServiceFeature.FixtureData fixtureData, E2EChatAppSpecFlow_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Services", "FriendService", "A service for creating, accepting, and cancelling friendships", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create and accept Friendships")]
        [Xunit.TraitAttribute("FeatureTitle", "FriendService")]
        [Xunit.TraitAttribute("Description", "Create and accept Friendships")]
        [Xunit.InlineDataAttribute("is not", "", "", "my user", "other user", "Created", new string[0])]
        [Xunit.InlineDataAttribute("is not", "", "", "other user", "my user", "Created", new string[0])]
        [Xunit.InlineDataAttribute("is", "my user", "is", "my user", "other user", "Nothing", new string[0])]
        [Xunit.InlineDataAttribute("is", "my user", "is not", "my user", "other user", "Nothing", new string[0])]
        [Xunit.InlineDataAttribute("is", "other user", "is", "my user", "other user", "Accepted", new string[0])]
        [Xunit.InlineDataAttribute("is", "other user", "is not", "my user", "other user", "Nothing", new string[0])]
        [Xunit.InlineDataAttribute("is", "my user", "is", "other user", "my user", "Accepted", new string[0])]
        [Xunit.InlineDataAttribute("is", "my user", "is not", "other user", "my user", "Nothing", new string[0])]
        [Xunit.InlineDataAttribute("is", "other user", "is", "other user", "my user", "Nothing", new string[0])]
        [Xunit.InlineDataAttribute("is", "other user", "is not", "other user", "my user", "Nothing", new string[0])]
        public virtual void CreateAndAcceptFriendships(string isFriendship, string friendshipMaker, string isPending, string sender, string receiver, string result, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("IsFriendship", isFriendship);
            argumentsOfScenario.Add("FriendshipMaker", friendshipMaker);
            argumentsOfScenario.Add("IsPending", isPending);
            argumentsOfScenario.Add("Sender", sender);
            argumentsOfScenario.Add("Receiver", receiver);
            argumentsOfScenario.Add("Result", result);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create and accept Friendships", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 4
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
        testRunner.Given(string.Format("there {0} a friendship between me and the other user, initiated by {1}, and the f" +
                            "riendship {2} pending", isFriendship, friendshipMaker, isPending), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
        testRunner.When(string.Format("{0} sends a create request to {1}", sender, receiver), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
        testRunner.Then(string.Format("the result is: {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                FriendServiceFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                FriendServiceFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
